export const ACTION_TYPES = {
    FETCH_START: "FETCH_START",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",
    STATE_UPDATED: "STATE_UPDATED",
    CHANGE_INPUT: "CHANGE_INPUT"
}