name: Stop, Build & Run updated container

on:
  push:
    branches: [ "master" ]

jobs:
  stop_build_run:
    runs-on: self-hosted
    env:
      IMAGE_NAME: reactaishoppinglist
      PORT: 4444
      DIR: c:\users\server\documents\servedtunnels\reactaishoppinglist
      API_KEY: ${{secrets.OPEN_API_KEY}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      #- name: Change to DIR
        #run: cd c:\users\server\documents\servedtunnels\${{env.IMAGE_NAME}}
      - name: Shut down current container
        #run: docker stop $(docker ps -q --filter "ancestor=${{env.IMAGE_NAME}}")
        #run: docker stop --filter "ancestor=reactaishoppinglist:latest" 
        run: |
          $containerIds = docker ps -q | ForEach-Object { 
            $container = docker inspect --format '{{.Id}} {{.Config.Image}}' $_
            if ($container -match "artimusmaximus/${{env.IMAGE_NAME}}:latest") { 
              docker stop $container.Split(" ")[0] 
              Write-Host "Container found and shutting down..."
            } else { Write-Host "No container found..." }
          }
      #- name: Build new container
        #run: docker build -t artimusmaximus/${{env.IMAGE_NAME}}:latest
      - name: pull updated container
        run: docker pull artimusmaximus/${{env.IMAGE_NAME}}:latest
      - name: Start new container
        run: docker run -e OPEN_API_KEY=${API_KEY} -d -p ${{env.PORT}}:${{env.PORT}} artimusmaximus/${{env.IMAGE_NAME}}:latest
